/**
 * Build script: compiles src/ → lib/ with esbuild.
 *
 * - Host half (src/index.ts)        → lib/index.js   (ESM, Node, peerDeps external)
 * - Client half (src/client/index.ts) → lib/client.js (wrapped in the
 *   window.__ModuleLoader__.load({ id, factory }) format that DSH's
 *   client-modules system reads; browser globals, no React dependency)
 *
 * lib/ is committed so installs don't need a build step.
 */
import { build } from 'esbuild';
import { readFile, writeFile, rm, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PLUGIN_ID = 'dsh-restart-button';

const EXTERNAL_HOST = [
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-settings',
  '@deepseek-ai/dsh-tools',
  '@deepseek-ai/schemastery',
];

async function main() {
  await mkdir(join(__dirname, 'lib'), { recursive: true });

  // ---- Host half ----
  await build({
    entryPoints: [join(__dirname, 'src/index.ts')],
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node22',
    external: EXTERNAL_HOST,
    outfile: join(__dirname, 'lib/index.js'),
    sourcemap: true,
    logLevel: 'info',
  });

  // ---- Client half ----
  // Step 1: bundle to a temp CJS file.
  //
  // `react` stays external: the DSH client module table seeds React as a
  // platform baseline module, so the factory's `require('react')` resolves it
  // at materialization. Bundling it would ship a second, incompatible React.
  const tmpPath = join(__dirname, 'lib/client.tmp.js');
  await build({
    entryPoints: [join(__dirname, 'src/client/index.tsx')],
    bundle: true,
    format: 'cjs',
    platform: 'browser',
    target: 'es2022',
    external: ['react'],
    // Classic transform: the JSX factory is the `createElement` this bundle
    // imports from React, so no react/jsx-runtime entry point is required.
    jsx: 'transform',
    jsxFactory: 'createElement',
    jsxFragment: 'Fragment',
    outfile: tmpPath,
    sourcemap: false, // we attach a map below by re-emitting is unnecessary; keep simple
    logLevel: 'info',
  });

  // Step 2: wrap in the DSH client-modules loader format.
  const clientCode = await readFile(tmpPath, 'utf8');
  const wrapped =
    '// AUTO-GENERATED by build.mjs. Do not edit.\n' +
    'window.__ModuleLoader__.load({\n' +
    '  id: ' + JSON.stringify(PLUGIN_ID) + ',\n' +
    '  factory: (require) => {\n' +
    '    var module = { exports: {} };\n' +
    '    var exports = module.exports;\n' +
    clientCode +
    '\n    return module.exports;\n' +
    '  }\n' +
    '});\n';
  await writeFile(join(__dirname, 'lib/client.js'), wrapped, 'utf8');
  await rm(tmpPath, { force: true });

  console.log('[build] done: lib/index.js, lib/client.js');
}

main().catch((err) => {
  console.error('[build] failed:', err);
  process.exit(1);
});
