// AUTO-GENERATED by build.mjs. Do not edit.
window.__ModuleLoader__.load({
  id: "@pangxitong/dsh-restart-button",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.tsx
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(index_exports);
var import_react = require("react");
var PLUGIN_ID = "dsh-restart-button";
var SLOT_HEADER_UTILITIES = "conversation.session.header.utilities";
var HOST_CLOSE = "/" + PLUGIN_ID + "/close";
var HOST_RESTART = "/" + PLUGIN_ID + "/restart";
var inject = ["slots"];
function PowerIcon() {
  return /* @__PURE__ */ (0, import_react.createElement)(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      viewBox: "0 0 24 24",
      width: "16",
      height: "16",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      "aria-hidden": "true"
    },
    /* @__PURE__ */ (0, import_react.createElement)("path", { d: "M12 2v10" }),
    /* @__PURE__ */ (0, import_react.createElement)("path", { d: "M18.36 6.64a9 9 0 1 1-12.73 0" })
  );
}
function CloseIcon() {
  return /* @__PURE__ */ (0, import_react.createElement)(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      viewBox: "0 0 24 24",
      width: "15",
      height: "15",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      "aria-hidden": "true"
    },
    /* @__PURE__ */ (0, import_react.createElement)("rect", { x: "5", y: "5", width: "14", height: "14", rx: "2" }),
    /* @__PURE__ */ (0, import_react.createElement)("path", { d: "M9 9l6 6M15 9l-6 6" })
  );
}
function RestartIcon() {
  return /* @__PURE__ */ (0, import_react.createElement)(
    "svg",
    {
      xmlns: "http://www.w3.org/2000/svg",
      viewBox: "0 0 24 24",
      width: "15",
      height: "15",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      "aria-hidden": "true"
    },
    /* @__PURE__ */ (0, import_react.createElement)("path", { d: "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8" }),
    /* @__PURE__ */ (0, import_react.createElement)("path", { d: "M21 3v5h-5" })
  );
}
function MenuRow(props) {
  const [hover, setHover] = (0, import_react.useState)(false);
  return /* @__PURE__ */ (0, import_react.createElement)(
    "button",
    {
      type: "button",
      onClick: props.onClick,
      disabled: props.disabled,
      onMouseEnter: () => setHover(true),
      onMouseLeave: () => setHover(false),
      style: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        width: "100%",
        padding: "7px 10px",
        border: "none",
        borderRadius: "7px",
        background: hover && !props.disabled ? "color-mix(in srgb, currentColor 12%, transparent)" : "transparent",
        color: props.color,
        cursor: props.disabled ? "default" : "pointer",
        opacity: props.disabled ? 0.6 : 1,
        font: "inherit",
        fontSize: "13px",
        fontWeight: 500,
        textAlign: "left",
        whiteSpace: "nowrap",
        transition: "background 0.12s"
      }
    },
    props.icon,
    /* @__PURE__ */ (0, import_react.createElement)("span", null, props.label)
  );
}
function closePage() {
  try {
    window.open("", "_self", "");
  } catch {
  }
  try {
    window.close();
  } catch {
  }
}
function PowerMenu() {
  const [open, setOpen] = (0, import_react.useState)(false);
  const [busy, setBusy] = (0, import_react.useState)(null);
  const [done, setDone] = (0, import_react.useState)(null);
  const [hover, setHover] = (0, import_react.useState)(false);
  const rootRef = (0, import_react.useRef)(null);
  (0, import_react.useEffect)(() => {
    if (!open) return;
    const onPointerDown = (event) => {
      const root = rootRef.current;
      if (root && !root.contains(event.target)) setOpen(false);
    };
    const onKeyDown = (event) => {
      if (event.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onPointerDown, true);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown, true);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);
  const send = async (route, kind) => {
    if (busy) return;
    setBusy(kind);
    setOpen(false);
    try {
      await fetch(route, { method: "POST", keepalive: true });
    } catch {
    }
    closePage();
    window.setTimeout(() => setDone(kind), 400);
  };
  const title = "\u5173\u95ED / \u91CD\u542F DeepSeek Harness";
  if (done) {
    return /* @__PURE__ */ (0, import_react.createElement)(
      "div",
      {
        style: {
          position: "fixed",
          inset: 0,
          zIndex: 2147483647,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          gap: "16px",
          background: "var(--dsw-alias-bg-base, #ffffff)",
          color: "inherit",
          fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif'
        }
      },
      /* @__PURE__ */ (0, import_react.createElement)("div", { style: { fontSize: "15px", fontWeight: 600 } }, done === "restart" ? "DSH \u6B63\u5728\u91CD\u542F\u2026" : "DSH \u5DF2\u5173\u95ED"),
      /* @__PURE__ */ (0, import_react.createElement)("div", { style: { fontSize: "13px", opacity: 0.7 } }, done === "restart" ? "\u670D\u52A1\u91CD\u542F\u540E\u8BF7\u5237\u65B0\u6B64\u9875\u9762" : "\u6B64\u9875\u9762\u53EF\u4EE5\u5173\u95ED\u4E86"),
      /* @__PURE__ */ (0, import_react.createElement)(
        "button",
        {
          type: "button",
          onClick: closePage,
          style: {
            padding: "8px 18px",
            border: "1px solid color-mix(in srgb, currentColor 22%, transparent)",
            borderRadius: "8px",
            background: "color-mix(in srgb, currentColor 8%, transparent)",
            color: "inherit",
            cursor: "pointer",
            font: "inherit",
            fontSize: "13px",
            fontWeight: 500
          }
        },
        "\u5173\u95ED\u6B64\u9875\u9762"
      )
    );
  }
  return /* @__PURE__ */ (0, import_react.createElement)("span", { ref: rootRef, style: { position: "relative", display: "inline-flex", alignItems: "center" } }, /* @__PURE__ */ (0, import_react.createElement)(
    "button",
    {
      type: "button",
      title,
      "aria-label": title,
      "aria-haspopup": "menu",
      "aria-expanded": open,
      onClick: () => setOpen((value) => !value),
      onMouseEnter: () => setHover(true),
      onMouseLeave: () => setHover(false),
      style: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        width: "30px",
        height: "30px",
        padding: 0,
        border: "none",
        borderRadius: "8px",
        background: open || hover ? "color-mix(in srgb, currentColor 12%, transparent)" : "transparent",
        color: "inherit",
        cursor: "pointer",
        flexShrink: 0,
        transition: "background 0.12s"
      }
    },
    /* @__PURE__ */ (0, import_react.createElement)(PowerIcon, null)
  ), open ? /* @__PURE__ */ (0, import_react.createElement)(
    "div",
    {
      role: "menu",
      style: {
        position: "absolute",
        top: "calc(100% + 6px)",
        right: 0,
        zIndex: 2147483e3,
        display: "flex",
        flexDirection: "column",
        gap: "2px",
        minWidth: "136px",
        padding: "6px",
        border: "1px solid color-mix(in srgb, currentColor 18%, transparent)",
        borderRadius: "10px",
        background: "var(--dsw-alias-bg-elevated, #ffffff)",
        boxShadow: "0 8px 28px rgba(0, 0, 0, 0.28)",
        color: "inherit",
        fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif'
      }
    },
    /* @__PURE__ */ (0, import_react.createElement)(
      MenuRow,
      {
        label: busy === "restart" ? "\u91CD\u542F\u4E2D\u2026" : "\u91CD\u542F",
        icon: /* @__PURE__ */ (0, import_react.createElement)(RestartIcon, null),
        color: "inherit",
        disabled: busy !== null,
        onClick: () => send(HOST_RESTART, "restart")
      }
    ),
    /* @__PURE__ */ (0, import_react.createElement)(
      MenuRow,
      {
        label: busy === "close" ? "\u5173\u95ED\u4E2D\u2026" : "\u5173\u95ED",
        icon: /* @__PURE__ */ (0, import_react.createElement)(CloseIcon, null),
        color: "#e5484d",
        disabled: busy !== null,
        onClick: () => send(HOST_CLOSE, "close")
      }
    )
  ) : null);
}
function apply(ctx) {
  ctx.effect(
    () => ctx.slots.inject(
      SLOT_HEADER_UTILITIES,
      () => ctx.slots.register(
        {
          name: SLOT_HEADER_UTILITIES,
          id: PLUGIN_ID + ":power",
          order: 10,
          registrant: PLUGIN_ID
        },
        () => /* @__PURE__ */ (0, import_react.createElement)(PowerMenu, null)
      )
    ),
    PLUGIN_ID + ": header power menu"
  );
}

    return module.exports;
  }
});
