// AUTO-GENERATED by build.mjs. Do not edit.
window.__ModuleLoader__.load({
  id: "dsh-restart-button",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/client/index.ts
var index_exports = {};
__export(index_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(index_exports);
var PLUGIN_ID = "dsh-restart-button";
var MARK_ATTR = "data-dsh-restart-button";
var HOST_CLOSE = "/" + PLUGIN_ID + "/close";
var HOST_RESTART = "/" + PLUGIN_ID + "/restart";
var POWER_ICON_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v10"/><path d="M18.36 6.64a9 9 0 1 1-12.73 0"/></svg>';
var CLOSE_ICON_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="5" width="14" height="14" rx="2"/><path d="M9 9l6 6M15 9l-6 6"/></svg>';
var RESTART_ICON_SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"/><path d="M21 3v5h-5"/></svg>';
function svgDataUri(svg) {
  return "data:image/svg+xml," + encodeURIComponent(svg);
}
function buildPopover(onClose, onRestart) {
  const popover = document.createElement("div");
  popover.setAttribute(MARK_ATTR, "popover");
  Object.assign(popover.style, {
    position: "fixed",
    zIndex: "2147483647",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    padding: "6px",
    borderRadius: "10px",
    // Theme-agnostic surface: translucent + blur, currentColor borders.
    background: "color-mix(in srgb, var(--dsw-alias-bg-elevated, #ffffff) 92%, transparent)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    border: "1px solid color-mix(in srgb, currentColor 18%, transparent)",
    boxShadow: "0 8px 28px rgba(0,0,0,0.28)",
    color: "inherit",
    minWidth: "132px",
    fontFamily: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
    fontSize: "13px"
  });
  const mkButton = (label, icon, color) => {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.setAttribute(MARK_ATTR, "action");
    Object.assign(btn.style, {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      padding: "7px 10px",
      borderRadius: "7px",
      border: "none",
      background: "transparent",
      color,
      cursor: "pointer",
      fontSize: "13px",
      fontWeight: "500",
      whiteSpace: "nowrap",
      transition: "background 0.12s",
      width: "100%",
      textAlign: "left"
    });
    const img = document.createElement("img");
    img.src = svgDataUri(icon);
    Object.assign(img.style, { width: "15px", height: "15px", flexShrink: "0" });
    img.alt = "";
    const span = document.createElement("span");
    span.textContent = label;
    btn.appendChild(img);
    btn.appendChild(span);
    btn.addEventListener("mouseenter", () => {
      btn.style.background = "color-mix(in srgb, currentColor 12%, transparent)";
    });
    btn.addEventListener("mouseleave", () => {
      btn.style.background = "transparent";
    });
    return btn;
  };
  const closeBtn = mkButton("\u5173\u95ED", CLOSE_ICON_SVG, "#e5484d");
  const restartBtn = mkButton("\u91CD\u542F", RESTART_ICON_SVG, "inherit");
  closeBtn.dataset.action = "close";
  restartBtn.dataset.action = "restart";
  closeBtn.addEventListener("click", onClose);
  restartBtn.addEventListener("click", onRestart);
  popover.appendChild(restartBtn);
  popover.appendChild(closeBtn);
  return popover;
}
function buildPowerButton() {
  const btn = document.createElement("button");
  btn.type = "button";
  btn.setAttribute(MARK_ATTR, "power");
  btn.title = "\u5173\u95ED / \u91CD\u542F DeepSeek Harness";
  btn.setAttribute("aria-label", "\u5173\u95ED / \u91CD\u542F DeepSeek Harness");
  Object.assign(btn.style, {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    padding: "0",
    borderRadius: "8px",
    border: "none",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    flexShrink: "0",
    transition: "background 0.12s"
  });
  const img = document.createElement("img");
  img.src = svgDataUri(POWER_ICON_SVG);
  Object.assign(img.style, { width: "18px", height: "18px", display: "block" });
  img.alt = "";
  btn.appendChild(img);
  btn.addEventListener("mouseenter", () => {
    btn.style.background = "color-mix(in srgb, currentColor 14%, transparent)";
  });
  btn.addEventListener("mouseleave", () => {
    btn.style.background = "transparent";
  });
  return btn;
}
function findToolbarContainer() {
  const candidates = [
    document.querySelector('[role="toolbar"]'),
    document.querySelector("header"),
    // Common DSH / generic app-bar class hints.
    document.querySelector('[class*="toolbar" i]'),
    document.querySelector('[class*="appbar" i]'),
    document.querySelector('[class*="topbar" i]'),
    document.querySelector('[class*="header-bar" i]')
  ];
  for (const c of candidates) {
    if (c) return c;
  }
  return null;
}
function mountInto(toolbar) {
  if (toolbar.querySelector("[" + MARK_ATTR + '="power"')) return false;
  const btn = buildPowerButton();
  const wrap = document.createElement("div");
  wrap.setAttribute(MARK_ATTR, "wrap");
  Object.assign(wrap.style, {
    display: "inline-flex",
    alignItems: "center",
    marginLeft: "auto",
    flexShrink: "0"
  });
  wrap.appendChild(btn);
  try {
    toolbar.appendChild(wrap);
  } catch {
    return false;
  }
  let popover = null;
  const closePopover = () => {
    if (popover) {
      popover.remove();
      popover = null;
    }
  };
  const positionPopover = () => {
    if (!popover) return;
    const rect = btn.getBoundingClientRect();
    const pw = popover.offsetWidth;
    const ph = popover.offsetHeight;
    let left = rect.right - pw;
    let top = rect.bottom + 6;
    if (left < 8) left = 8;
    if (top + ph > window.innerHeight - 8) {
      top = Math.max(8, rect.top - ph - 6);
    }
    popover.style.left = left + "px";
    popover.style.top = top + "px";
  };
  const callHost = async (route, onBusy) => {
    try {
      onBusy();
      await fetch(route, { method: "POST" });
    } catch {
    }
  };
  btn.addEventListener("click", (e) => {
    e.stopPropagation();
    if (popover) {
      closePopover();
      return;
    }
    popover = buildPopover(
      // Close
      async () => {
        if (!popover) return;
        const actionBtn = popover.querySelector(
          '[data-action="close"]'
        );
        callHost(HOST_CLOSE, () => {
          if (actionBtn) {
            const span = actionBtn.querySelector("span");
            if (span) span.textContent = "\u5173\u95ED\u4E2D\u2026";
            actionBtn.style.pointerEvents = "none";
            actionBtn.style.opacity = "0.6";
          }
        });
      },
      // Restart
      async () => {
        if (!popover) return;
        const actionBtn = popover.querySelector(
          '[data-action="restart"]'
        );
        callHost(HOST_RESTART, () => {
          if (actionBtn) {
            const span = actionBtn.querySelector("span");
            if (span) span.textContent = "\u91CD\u542F\u4E2D\u2026";
            actionBtn.style.pointerEvents = "none";
            actionBtn.style.opacity = "0.6";
          }
        });
      }
    );
    document.body.appendChild(popover);
    requestAnimationFrame(positionPopover);
  });
  document.addEventListener(
    "click",
    (e) => {
      if (!popover) return;
      if (popover.contains(e.target) || btn === e.target) return;
      closePopover();
    },
    true
  );
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") closePopover();
  });
  window.addEventListener("scroll", positionPopover, true);
  window.addEventListener("resize", positionPopover);
  return true;
}
function mountFloating() {
  if (document.querySelector("[" + MARK_ATTR + '="power"')) return false;
  const host = document.createElement("div");
  host.setAttribute(MARK_ATTR, "floating-host");
  Object.assign(host.style, {
    position: "fixed",
    top: "12px",
    right: "12px",
    zIndex: "2147483646",
    display: "inline-flex"
  });
  document.body.appendChild(host);
  mountInto(host);
  const btn = host.querySelector("[" + MARK_ATTR + '="power"]');
  if (btn) {
    Object.assign(btn.style, {
      width: "36px",
      height: "36px",
      borderRadius: "50%",
      background: "color-mix(in srgb, var(--dsw-alias-bg-elevated, #ffffff) 92%, transparent)",
      border: "1px solid color-mix(in srgb, currentColor 18%, transparent)",
      boxShadow: "0 2px 10px rgba(0,0,0,0.18)"
    });
  }
  return true;
}
function ensureButton() {
  if (document.querySelector("[" + MARK_ATTR + '="power"')) return true;
  const toolbar = findToolbarContainer();
  if (toolbar) {
    return mountInto(toolbar);
  }
  return false;
}
var inject = [];
function apply(_ctx) {
  if (typeof document === "undefined" || typeof window === "undefined") return;
  if (ensureButton()) return;
  const observer = new MutationObserver(() => {
    if (ensureButton()) {
      observer.disconnect();
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });
  setTimeout(() => {
    if (!document.querySelector("[" + MARK_ATTR + '="power"')) {
      mountFloating();
      observer.disconnect();
    }
  }, 8e3);
}

    return module.exports;
  }
});
